title: Of vars and dirs
description: > 
  An experiment in blogging, Jekyll and Github pages.
baseurl: "" 
url: "https://enricomiccoli.com" 

# Build settings
markdown: kramdown

sass:
    style: compact 

exclude:
    - LICENSE
    - Gemfile
    - Gemfile.lock

plugins:
    - jekyll-redirect-from
