title: Of vars and dirs
description: > 
  An experiment in blogging, Jekyll and Github pages.
baseurl: "" 
url: "enricomiccoli.github.io" 

# Build settings
markdown: kramdown

sass:
    style: compact 

exclude:
    - LICENSE
    - Gemfile
    - Gemfile.lock
